name: "Checks: Reusable"

on:
  workflow_call:
    secrets:
      TOKEN_ENCRYPTION_KEY:
        required: true
      TOKEN_SIGNING_KEY:
        required: true
      RESEND_API_KEY:
        required: true
      TURNSTILE_SECRET_KEY:
        required: true

jobs:
  format:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          cache-key: format
      - run: pnpm run format:check

  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          cache-key: lint
      - run: pnpm run lint

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
        with:
          cache-key: test
      - name: Configure .dev.vars
        run: |
          cat <<EOF > apps/api/.dev.vars
          TOKEN_ENCRYPTION_KEY=${{ secrets.TOKEN_ENCRYPTION_KEY }}
          TOKEN_SIGNING_KEY=${{ secrets.TOKEN_SIGNING_KEY }}
          RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}
          TURNSTILE_SECRET_KEY=${{ secrets.TURNSTILE_SECRET_KEY }}
          EOF
      - run: pnpm run test:run -- --reporter=default --reporter=github-actions
        env:
          TEST_DEV_VARS: ${{ secrets.TEST_DEV_VARS }}
